# Generated by Django 2.2.16 on 2021-12-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20211220_0749'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='not_subscription_by_myself',
        ),
    ]
